macOS: abandon 'fp.h' when compiling 'libpng'
Our CI has been broken with this error under macOS:

`./pngconf.h:354:16: fatal error: 'fp.h' file not found`

GitHub user 'ryandesign' helpfully opened issue #110 back in October,
addressing this very error message!  One solution would be a full
upgrade of 'libpng', which looks daunting; I have no idea how I would
verify whether all the changes in the library are safe for all the old
systems where folks compile XEphem.

The other possible approach is simply to disable the tangle of `#if`
guards that try to include `fp.h` under macOS.

Here I've taken the latter approach, but it does involve risk: what if
there's still an XEphem user on an old 68k or PowerPC system, for whom
this will be a breaking change?  We will just have to cross our fingers,
and be prepared to support them if they open an issue.